name: revexa_backend
description: Backend API for Revexa Barber
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  mysql1: ^0.20.0
  crypto: ^3.0.3
  jaguar_jwt: ^3.0.0
  json_annotation: ^4.8.1
  shelf_hotreload: ^1.6.0

dev_dependencies:
  lints: ^2.1.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
