name: revexa_barber
description: Sistema de gestÃ£o para barbearias
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.5
  intl: ^0.20.2
  url_launcher: ^6.3.1
  fl_chart: ^0.69.0
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
